//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Tb
    {
        public int NO_F { get; set; }
        public string Title_F { get; set; }
        public string Content_F { get; set; }
        public Nullable<System.DateTime> JoinTime_F { get; set; }
        public Nullable<int> ViewCount_F { get; set; }
        public int AccountNO_F { get; set; }
    }
}
